### PR TITLE
Update sourcestyle.css

### PR DESCRIPTION
**Pull request by SRGOM**
Fix font, was not using monospace earlier.

### CODE REVIEW

**Comment by dobkeratops** [comment]
hi i just tried to merge, it doesn't work;
do you actually have this compiling? if so i'd happily replace with your code.
i was considering having another bash at trying to update it myself.. but it would probably be a lot of work.

**Comment by dobkeratops** [comment]
ok that merge worked,

**Comment by SRGOM** [comment]
No worries, feel free to let me know if there are any problems. Did you generate the first version programmatically btw?

**Comment by dobkeratops** [comment]
>>"Did you generate the first version programatically"..

if you mean the HTML output: - yes, this program reads rust source & presents it,
if you mean the CSS file that you changed: I'm not sure if I just cut-pasted it or something , I can't remember; 
if I ever get this working again I'll certainly fix it.  I'm getting interested in rust again but anti-bitrotting this pre 1.0 code is very daunting, and I suspect efforts in the community toward IDE's etc may have yielded better ways of doing all this.

**Comment by dobkeratops** [comment]
ok: rust2html.rs  , it includes!() this css file .. i.e. no , it is not programatically generated, but the program does include it and spit it out itself along with the generated html output.

**Pull request merged**
